name: simplereader
description: "A new Flutter project."
publish_to: 'none'
version: 1.23.12+24

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.13
  file_manager: ^1.0.2
  file_picker: ^10.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.2
  flutter_svg: ^2.0.10+1
  go_router: ^16.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path: ^1.9.0
  path_provider: ^2.1.3
  pdfrx: ^2.1.3
  permission_handler: ^12.0.1
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/android/app_logo.png"
  adaptive_icon_foreground: "assets/icons/android/app_logo.png"
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/

  fonts:
    - family: GideonRoman
      fonts:
        - asset: assets/fonts/GideonRoman-Regular.ttf
    
    - family: PublicSans
      fonts:
        - asset:  assets/fonts/PublicSans-VariableFont_wght.ttf

