name: simplereader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  file_manager: ^1.0.2
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_document_picker: ^5.2.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  path_provider: ^2.1.3
  pdfrx: ^1.0.67
  permission_handler: ^11.3.1
  share_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/example.pdf
    - assets/image/
    - assets/icons/

  fonts:
    - family: GideonRoman
      fonts:
        - asset: assets/fonts/GideonRoman-Regular.ttf
    
    - family: PublicSans
      fonts:
        - asset:  assets/fonts/PublicSans-VariableFont_wght.ttf

